networks:
  network:
    driver: bridge
    external: false

services:
  turborepo-next:
    container_name: development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    networks:
      - network
