networks:
  network:
    driver: bridge
    external: false

services:
  turborepo-next:
    container_name: prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    networks:
      - network
