version: '4.0'

networks:
  test_network:
    driver: bridge

services:
  test:
    container_name: development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    networks:
      - test_network
    command: sh -c "pnpm run build && pnpm run start"
